verboice_url: 'http://localhost:3001'
verboice_first_audio_file: '1533197539228'
wit_token: 'WIT_APPLICATION_TOKEN'
case_key: "case"
symptoms_key: "symptoms"
number_of_case_key: "number_of_case"
location_key: "place"
