url_host: http://localhost:3000
timezone: 'Asia/Bangkok'
datetime_format: '%Y-%m-%d %H:%M'
verboice:
  url: 'http://localhost:3001'
  first_audio_file: '1536659392294'
wit:
  access_token: 'WIT_APPLICATION_TOKEN'
  symptoms_key: "symptom"
  case_key: "case"
  location_key: "place"
default_page_size: 10

